gText_Birch_Welcome::
	.string "Hello! Welcome Eco Surveyor!\p"
	.string "My name is PROFESSOR BIRCH and I'll be\n"
	.string "your guide to the world of POKéMON.\p"
	.string "I'll also be serving as a messenger\n"
	.string "for Earth's New Hope Foundation.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world was widely inhabited by\n"
	.string "POKéMON and humans alike.\p"
	.string "For centuries humans lived peacefully\n"
	.string "alongside POKéMON, until the Great War.\p"
	.string "Some humans wanted to control POKéMON\n"
	.string "and the great powers they wield.\p"
	.string "They used these powers to spread fear\n"
	.string "across the many regions of Earth.\p"
	.string "Other humans and POKéMON fought back\n"
	.string "against this tyranny.\p"
	.string "The ensuing battles ravaged the planet,\n"
	.string "wiping out entire regions and species\l"
	.string "of POKéMON.\p"
	.string "The planets ecosystems completely\n"
	.string "collapsed and the remnants of humanity\l"
	.string "were left picking up the pieces.\p"
	.string "The Birch family started\n"
	.string "Earth's New Hope Foundation\l"
	.string "nearly 100 years ago.\p"
	.string "In that time we developed the Arks.\p"
	.string "These experimental miniature regions\n"
	.string "have their own POKéMON populations.\p"
	.string "Unfortunately, these populations have\n"
	.string "failed to recreate a living ecosystem\l"
	.string "that could be spread across Earth.\p"
	.string "I've been sent to check Ark 42\n"
	.string "and see if it has collapsed\l"
	.string "like the Arks before it.\p"
	.string "The Foundation has assigned you as\p"
	.string "my assistant.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Thanks to my blabbing, I don't yet\n"
	.string "know anything about you.$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, nice to meet you {PLAYER}{KUN}.\p"
	.string "I'm excited to work with you and\n"
	.string "survey the wilds of Ark 42.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Take courage, and venture into the\n"
	.string "wilds of Ark 42 to survey the remaining\l"
	.string "POKéMON and maybe even save the world.\p"
	.string "$"
