PetalburgCity_House1_MapScripts::
	.byte 0

PetalburgCity_House1_EventScript_Man::
	msgbox PetalburgCity_House1_Text_TravelingIsWonderful, MSGBOX_NPC
	end

PetalburgCity_House1_EventScript_Woman::
	msgbox PetalburgCity_House1_Text_GoOnAdventure, MSGBOX_NPC
	end

PetalburgCity_House1_Text_TravelingIsWonderful:
	.string "Traveling is wonderful!\p"
	.string "When I was young, I lived in a van\n"
	.string "with Pico, my Poochyena.$"

PetalburgCity_House1_Text_GoOnAdventure:
	.string "The Professor came through here\n"
	.string "yesterday with a dozen Lotads.\p"
	.string "He said he was trying to find a shiny\n"
	.string "one with the DexNav's chaining feature.$"

